dist: xenial

git:
  depth: false

language: python

python:
 - 3.6

install:
  - travis_retry pip install -r requirements.txt --progress-bar off
  # install testing requirements
  - travis_retry pip install -r requirements-test.txt --progress-bar off

script:
  - python -m pytest --cov=deepcell_applications --pep8

after_success:
  - coveralls
